### ISSUE TITLE
TextArea

### ISSUE THREAD

**Issue by Jose-Jaime-Castaneda** [ramonchis47/Adogtame#3]
No existe el textArea en Recat Native, asi que puse un TextInput con multilinea, pero te deja seguir escribiendo aunque ya te hayas pasado del numero maximo de lineas que puse, te toca resolverlo, yo ya lo puse.

**Comment by Erick-Hernandez-Ortega** [comment]
en que parte o componente?

**Comment by Jose-Jaime-Castaneda** [comment]
En el principal
Donde puse el botón flotante

**Comment by ramonchis47** [comment]
### Ya quedo
**Era poner MaxLenght={} 😉**

**Comment by Erick-Hernandez-Ortega** [comment]
### Ya quedo
**Era poner MaxLenght={} 😉**
